-- MySQL Script generated by MySQL Workbench
-- Tue Apr  2 15:23:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendor` (
  `VendorID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `DeviceID` INT NULL,
  PRIMARY KEY (`VendorID`),
  UNIQUE INDEX `Vendor ID_UNIQUE` (`VendorID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Devices` (
  `Device ID` INT NOT NULL,
  `DeviceType ID` VARCHAR(45) NULL,
  `Vendor_Vendor ID` INT NOT NULL,
  `Leased` TINYINT NOT NULL,
  `StartDate` DATE NULL,
  `EndDate` DATE NULL,
  PRIMARY KEY (`Device ID`),
  UNIQUE INDEX `Device ID_UNIQUE` (`Device ID` ASC) VISIBLE,
  INDEX `fk_Devices_Vendor_idx` (`Vendor_Vendor ID` ASC) VISIBLE,
  CONSTRAINT `fk_Devices_Vendor`
    FOREIGN KEY (`Vendor_Vendor ID`)
    REFERENCES `mydb`.`Vendor` (`VendorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `CityID` VARCHAR(45) NOT NULL,
  `CountryID` VARCHAR(45) NOT NULL,
  `Zipcode` VARCHAR(45) NULL,
  `Address_AddressID` VARCHAR(45) NOT NULL,
  `Address_Country_CountryID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CityID`, `Address_AddressID`, `Address_Country_CountryID`),
  INDEX `fk_City_Address1_idx` (`Address_AddressID` ASC, `Address_Country_CountryID` ASC) VISIBLE,
  CONSTRAINT `fk_City_Address1`
    FOREIGN KEY (`Address_AddressID` , `Address_Country_CountryID`)
    REFERENCES `mydb`.`Address` (`AddressID` , `Country_CountryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Country` (
  `CountryID` VARCHAR(45) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `City_CityID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CountryID`, `City_CityID`),
  INDEX `fk_Country_City1_idx` (`City_CityID` ASC) VISIBLE,
  CONSTRAINT `fk_Country_City1`
    FOREIGN KEY (`City_CityID`)
    REFERENCES `mydb`.`City` (`CityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `AddressID` VARCHAR(45) NOT NULL,
  `CityID` VARCHAR(45) NOT NULL,
  `CountryID` VARCHAR(45) NULL,
  `Zipcode` VARCHAR(45) NULL,
  `Addresscol` VARCHAR(45) NULL,
  `Country_CountryID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AddressID`, `Country_CountryID`),
  INDEX `fk_Address_Country1_idx` (`Country_CountryID` ASC) VISIBLE,
  CONSTRAINT `fk_Address_Country1`
    FOREIGN KEY (`Country_CountryID`)
    REFERENCES `mydb`.`Country` (`CountryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Office` (
  `OfficeID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `AddressID` VARCHAR(45) NULL,
  `Address_AddressID` VARCHAR(45) NOT NULL,
  `Address_Country_CountryID` VARCHAR(45) NOT NULL,
  `Address_AddressID1` VARCHAR(45) NOT NULL,
  `Address_Country_CountryID1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OfficeID`, `Address_AddressID`, `Address_Country_CountryID`, `Address_AddressID1`, `Address_Country_CountryID1`),
  UNIQUE INDEX `Office ID_UNIQUE` (`OfficeID` ASC) VISIBLE,
  INDEX `fk_Office_Address1_idx` (`Address_AddressID1` ASC, `Address_Country_CountryID1` ASC) VISIBLE,
  CONSTRAINT `fk_Office_Address1`
    FOREIGN KEY (`Address_AddressID1` , `Address_Country_CountryID1`)
    REFERENCES `mydb`.`Address` (`AddressID` , `Country_CountryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Device Assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Device Assignment` (
  `DeviceID` INT NOT NULL,
  `EmployeeID` INT NOT NULL,
  `OfficeID` INT NULL,
  `Floor` INT NULL,
  `Devices_Device_ID` INT NOT NULL,
  `Devices_Vendor_Vendor ID` INT NOT NULL,
  `Office_Office ID` INT NOT NULL,
  PRIMARY KEY (`DeviceID`, `EmployeeID`),
  UNIQUE INDEX `Device ID_UNIQUE` (`DeviceID` ASC) VISIBLE,
  INDEX `fk_Device Assignment_Devices1_idx` (`Devices_Device_ID` ASC, `Devices_Vendor_Vendor ID` ASC) VISIBLE,
  INDEX `fk_Device Assignment_Office1_idx` (`Office_Office ID` ASC) VISIBLE,
  CONSTRAINT `fk_Device Assignment_Devices1`
    FOREIGN KEY (`Devices_Device_ID` , `Devices_Vendor_Vendor ID`)
    REFERENCES `mydb`.`Devices` (`Device ID` , `Vendor_Vendor ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Device Assignment_Office1`
    FOREIGN KEY (`Office_Office ID`)
    REFERENCES `mydb`.`Office` (`OfficeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `EmployeeID` INT NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  `OfficeID` INT NULL,
  `Office_Office ID` INT NOT NULL,
  `Device Assignment_Device ID` INT NOT NULL,
  `Device Assignment_Devices_Device ID` INT NOT NULL,
  `Device_Assignment_Devices_Vendor_Vendor ID` INT NOT NULL,
  `Device_Assignment_Office_Office ID` INT NOT NULL,
  PRIMARY KEY (`EmployeeID`, `Office_Office ID`, `Device Assignment_Device ID`, `Device Assignment_Devices_Device ID`, `Device_Assignment_Devices_Vendor_Vendor ID`, `Device_Assignment_Office_Office ID`),
  UNIQUE INDEX `Employee ID_UNIQUE` (`EmployeeID` ASC) VISIBLE,
  INDEX `fk_Employee_Office1_idx` (`Office_Office ID` ASC) VISIBLE,
  INDEX `fk_Employee_Device Assignment1_idx` (`Device Assignment_Device ID` ASC, `Device Assignment_Devices_Device ID` ASC, `Device_Assignment_Devices_Vendor_Vendor ID` ASC, `Device_Assignment_Office_Office ID` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Office1`
    FOREIGN KEY (`Office_Office ID`)
    REFERENCES `mydb`.`Office` (`OfficeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Device Assignment1`
    FOREIGN KEY (`Device Assignment_Device ID` , `Device Assignment_Devices_Device ID` , `Device_Assignment_Devices_Vendor_Vendor ID` , `Device_Assignment_Office_Office ID`)
    REFERENCES `mydb`.`Device Assignment` (`DeviceID` , `Devices_Device_ID` , `Devices_Vendor_Vendor ID` , `Office_Office ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Device Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Device Types` (
  `DeviceTypeID` INT NOT NULL,
  `DeviceType` VARCHAR(45) NULL,
  `Stock` INT NULL,
  `Required` INT NULL,
  `Devices_Device ID` INT NOT NULL,
  PRIMARY KEY (`DeviceTypeID`, `Devices_Device ID`),
  UNIQUE INDEX `idDevice Types_UNIQUE` (`DeviceTypeID` ASC) VISIBLE,
  INDEX `fk_Device Types_Devices1_idx` (`Devices_Device ID` ASC) VISIBLE,
  CONSTRAINT `fk_Device Types_Devices1`
    FOREIGN KEY (`Devices_Device ID`)
    REFERENCES `mydb`.`Devices` (`Device ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `mydb`.`category_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category_1` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
